### ISSUE TITLE
Не верно использовано разложение

### ISSUE THREAD

**Issue by pogorelov155** [maksimanom/react_trello#11]
https://github.com/maksimanom/react_trello/blob/5238b25c2ac11a8786723ce58e46f88a6b4396ca/src/utils/addBoard.js#L8

**Comment by maksimanom** [comment]
Should i create a new variable which =[...boards] and only then concat it?

**Comment by maksimanom** [comment]
changed it globally (bug with `id: null` was present) and used `prev` state in setBoards method
