### ISSUE TITLE
Нужно делать хук для компонента

### ISSUE THREAD

**Issue by pogorelov155** [maksimanom/react_trello#14]
https://github.com/maksimanom/react_trello/blob/5238b25c2ac11a8786723ce58e46f88a6b4396ca/src/Component/CardFullView/cardEdit.js#L65-L81

**Comment by maksimanom** [comment]
as I understand i need to create some custom hook "checkUserLogin", because i'm checking login status in different Components and must not to repeat it???

**Comment by maksimanom** [comment]
created custom hook
