### ISSUE TITLE
Switch case

### ISSUE THREAD

**Issue by pogorelov155** [maksimanom/react_trello#15]
https://github.com/maksimanom/react_trello/blob/5238b25c2ac11a8786723ce58e46f88a6b4396ca/src/Component/CardFullView/cardEdit.js#L86-L91

**Comment by maksimanom** [comment]
changed it with:
switch (e.target.name) {
      case "cardText":
        setCardText(e.target.value);
        break;
      case "cardDescription":
        setCardDescription(e.target.value);
        break;
      default:
        break;
    }

**Comment by maksimanom** [comment]
Changed it with:
`switch (e.target.name) {
      case "cardText":
        setCardText(e.target.value);
        break;
      case "cardDescription":
        setCardDescription(e.target.value);
        break;
      default:
        break;
    }`

**Comment by maksimanom** [comment]
done
