### ISSUE TITLE
Плохая практики. Стили нужно описывать в файлах для стилей

### ISSUE THREAD

**Issue by pogorelov155** [maksimanom/react_trello#4]
https://github.com/maksimanom/react_trello/blob/5238b25c2ac11a8786723ce58e46f88a6b4396ca/src/App.js#L9

**Comment by maksimanom** [comment]
Accomplished with MaterialUI overrides method:
overrides: {
    MuiCssBaseline: {
      "@global": {
        html: {
          height: "100%",
        },
        body: {
          height: "100%",
          "& #root": {
            height: "100%",
          },
        },
      },
    },
  },
