### ISSUE TITLE
Подумай как можно сделать без вложенных конструкций

### ISSUE THREAD

**Issue by pogorelov155** [maksimanom/react_trello#9]
https://github.com/maksimanom/react_trello/blob/5238b25c2ac11a8786723ce58e46f88a6b4396ca/src/utils/changeBoards.js#L15

**Comment by maksimanom** [comment]
i think we can duplicate array and then use .find method ?
ternary operator will not solve this problem

**Comment by maksimanom** [comment]
can i solve it with this?
const newBoards = [...boards];
  const board = newBoards.find((board) => board.id === parseInt(boardId));
  const card = board.tasks.find((card) => card.id === parseInt(cardId));
  card.text = cardText;
  card.description = cardDescription;
  card.dateEnd = new Date(cardDateEnd);
